[package]
name = "jlo"
version = "0.1.0"
repository = "https://github.com/sunsided/jlo"
edition = "2024"
publish = false

[dependencies]
serde = "1.0"
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
